### PR TITLE
Update to SDK 3.12.6

### PR DESCRIPTION
**Pull request by thomas-bamford**
*Warning* bebop_autonomy does not compile yet with this version. I will be working on bebop_autonomy tomorrow (June 23). Once bebop_autonomy compiles and is tested I will comment on this PR.

### CODE REVIEW

**Review by mani-monaj — APPROVED** [review]
Thanks @thomas-bamford . LGTM.

**Comment by thomas-bamford** [comment]
Compiles with bebop_autonomy on branch sdk-3-12. Have not tested on vehicles as of yet.

**Comment by mani-monaj** [comment]
@thomas-bamford Thanks @thomas-bamford. That's great! When the test is done, let's merge this branch. I will then trigger the release (as a Debian).

**Comment by thomas-bamford** [comment]
Ok great! I will be able to run tests this Friday on a Bebop 2.

**Comment by thomas-bamford** [comment]
Tests successfully passed on the Bebop 2.

**Comment by VINICIOSTALIN** [comment]
Excuse me, I'm doing a job on bebop 1 but I can not install bebop_autonomy I get errors when doing catkin build 
There is a solution to the error?

**Comment by thomas-bamford** [comment]
Hi, please check out the sdk-3-12 branch in the bebop_autonomy package (pr https://github.com/AutonomyLab/bebop_autonomy/pull/120). It has not yet been merged so there are some compiling errors with the master branch.

**Comment by VINICIOSTALIN** [comment]
Thank you, and there is a solution to work temporarily with another version or something?

**Comment by thomas-bamford** [comment]
Yes, please use the branch that I referenced. If you run into trouble please read the installation instructions included in the branch (this file [link](https://github.com/AutonomyLab/bebop_autonomy/blob/8392f055b7ef0205b357f0c2d4088389910a1151/docs/installation.rst).)

**Pull request merged**
